name: android-arm-cpu
on: [push, pull_request]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install attr
           export ANDROID_NDK=$ANDROID_HOME/ndk-bundle
           export ANDROID_SDK=$ANDROID_HOME/sdk
    - name: build
      run: ./scripts/build_android.sh