name: android-arm-cpu
on: [push, pull_request]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install attr
    - name: specify NDK
          uses: ravinderjangra/android-ndk-toolchain-setup@0.2
          with:
            api: '21'
            arch: 'x86'
            install-location: 'toolchains'
            force: true
    - name: build
      run: ./scripts/build_android.sh
