name: android-arm-cpu
on: [push, pull_request]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install attr
    - name: export
      run: export ANDROID_NDK=$ANDROID_HOME/ndk-bundle
    - name: test
      run: cd $ANDROID_HOME && ls && pwd
    - name: build
      run: ./scripts/build_android.sh