name: android-arm-cpu
on: [push, pull_request]
jobs:
  android-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install attr
           sudo apt-get remove cmake
    run: 
           export ANDROID_NDK=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
    - name: build
      run: ./scripts/build_android.sh
